package com.example.hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller    // This means that this class is a Controller
//在这里写就是大前缀
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserlRepository userlRepository;

    //一个方法
    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Userl n = new Userl();
        n.setName(name);
        n.setEmail(email);
        userlRepository.save(n);
        return "Saved";
    }
    //又一个方法
    @GetMapping(path="/all")
    public @ResponseBody Iterable<Userl> getAllUsers() {
        // This returns a JSON or XML with the users
        return userlRepository.findAll();
    }
}